services:
  db:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./images:/images
  server:
    image: postgrest/postgrest
    ports:
      - 3000:3000
    environment:
      PGRST_SERVER_HOST: 0.0.0.0 # necessary for `postgrest --ready` flag to work
      PGRST_DB_URI: postgres://postgres:example@db/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_JWT_SECRET: reallyreallyreallyreallyverysafe
      PGRST_DB_PRE_REQUEST: auth.check_token
    depends_on:
      - db