create table person (
    generated_id bigint generated always as identity primary key,
    overridable_id bigint generated by default as identity unique,
    height_cm numeric,
    height_in numeric generated always as (height_cm / 2.54),
    weight_kg numeric,
    weight_lb numeric generated always as (weight_kg * 2.2) stored
);