create schema api;

create table api.todo (
    id   int     primary key generated by default as identity,
    done boolean not null default false,
    task text    not null,
    due  timestamptz
);

create role authenticator noinherit login password 'mysecretpassword';

create role web_anon nologin;
grant usage on schema api to web_anon;
grant select on api.todo to web_anon;
grant web_anon to authenticator;

create role todo_user nologin;
grant usage on schema api to todo_user;
grant all on api.todo to todo_user;
grant todo_user to authenticator;

create schema auth;
grant usage on schema auth to web_anon, todo_user;

create or replace function auth.check_token() returns void
  language plpgsql
  as $$
begin
  if current_setting('request.jwt.claims', true)::json->>'email' =
     'disgruntled@mycompany.com' then
    raise insufficient_privilege
      using hint = 'Nope, we are on to you';
  end if;
end
$$;

create domain "text/html" as text;

create or replace function api.sanitize_html(text) returns text as $$
  select replace(replace(replace(replace(replace($1, '&', '&amp;'), '"', '&quot;'),'>', '&gt;'),'<', '&lt;'), '''', '&apos;')
$$ language sql;

create or replace function api.html_editable_task(_id int) returns "text/html" as $$
  select format ($html$
  <form id="edit-task-%1$s"
        hx-post="/rpc/change_todo_task"
        hx-headers='{"Accept": "text/html"}'
        hx-vals='{"_id": %1$s}'
        hx-target="#todo-list-area"
        hx-trigger="submit,focusout">
    <input id="task-%1$s" type="text" name="_task" value="%2$s" autofocus>
  </form>
  $html$,
    id,
    api.sanitize_html(task)
  )
  from api.todo
  where id = _id;
$$ language sql;

create or replace function api.html_todo(api.todo) returns text as $$
  select format($html$
    <div class="grid">
      <div id="todo-edit-area-%1$s">
        <form id="edit-task-state-%1$s"
              hx-post="/rpc/change_todo_state"
              hx-vals='{"_id": %1$s, "_done": %4$s}'
              hx-target="#todo-list-area"
              hx-trigger="click">
          <%2$s style="cursor: pointer">
            %3$s
          </%2$s>
        </form>
      </div>
      <div style="text-align: right">
        <button class="outline"
                hx-get="/rpc/html_editable_task"
                hx-vals='{"_id": "%1$s"}'
                hx-target="#todo-edit-area-%1$s"
                hx-trigger="click">
          <span>
            <ion-icon name="create"></ion-icon>
          </span>
        </button>
        <button class="outline contrast"
                hx-post="/rpc/delete_todo"
                hx-vals='{"_id": %1$s}'
                hx-target="#todo-list-area"
                hx-trigger="click">
          <span>
            <ion-icon name="trash" style="color: #f87171"></ion-icon>
          </span>
        </button>
      </div>
    </div>
    $html$,
    $1.id,
    case when $1.done then 's' else 'span' end,
    api.sanitize_html($1.task),
    (not $1.done)::text
  );
$$ language sql stable;

create or replace function api.html_all_todos() returns text as $$
  select coalesce(
    string_agg(api.html_todo(t), '<hr>' order by t.id),
    '<p><em>There is nothing else to do.</em></p>'
  )
  from api.todo t;
$$ language sql;

create or replace function api.add_todo(_task text) returns "text/html" as $$
  insert into api.todo(task) values (_task);
  select api.html_all_todos();
$$ language sql;

create or replace function api.change_todo_state(_id int, _done boolean) returns "text/html" as $$
  update api.todo set done = _done where id = _id;
  select api.html_all_todos();
$$ language sql;

create or replace function api.change_todo_task(_id int, _task text) returns "text/html" as $$
  update api.todo set task = _task where id = _id;
  select api.html_all_todos();
$$ language sql;

create or replace function api.delete_todo(_id int) returns "text/html" as $$
  delete from api.todo where id = _id;
  select api.html_all_todos();
$$ language sql;

create or replace function api.index() returns "text/html" as $$
  select $html$
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>PostgREST + HTMX To-Do List</title>
      <!-- Pico CSS for CSS styling -->
      <link href="https://cdn.jsdelivr.net/npm/@picocss/pico@next/css/pico.min.css" rel="stylesheet">
      <!-- htmx for AJAX requests -->
      <script src="https://unpkg.com/htmx.org"></script>
    </head>
    <body>
      <main class="container"
            style="max-width: 600px"
            hx-headers='{"Accept": "text/html"}'>
        <article>
          <h5 style="text-align: center;">
            PostgREST + HTMX To-Do List
          </h5>
          <form hx-post="/rpc/add_todo"
                hx-target="#todo-list-area"
                hx-trigger="submit"
                hx-on="htmx:afterRequest: this.reset()">
            <input type="text" name="_task" placeholder="Add a todo...">
          </form>
          <div id="todo-list-area">
            $html$
              || api.html_all_todos() ||
            $html$
          <div>
        </article>
      </main>
      <!-- Script for Ionicons icons -->
      <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
      <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
      <script>
        function getCookie(name) {
            const cookies = document.cookie.split(";");
            for (let cookie of cookies) {
                const [cookieName, cookieValue] = cookie.trim().split("=");
                if (cookieName === name) {
                    return decodeURIComponent(cookieValue);
                }
            }
            return null;
        }
        document.body.addEventListener("htmx:configRequest", function(evt) {
            const token = getCookie("token");
            if (token) {
                event.detail.headers["Authorization"] = "Bearer " + token;
            }
        });
      </script>
    </body>
    </html>
  $html$;
$$ language sql;

create extension byteamagic;

create table api.file (
    id   int   primary key generated by default as identity,
    type text  generated always as (byteamagic_mime(substr(blob, 0, 4100))) stored,
    name text  not null,
    blob bytea not null
);

grant all on api.file to web_anon;

create domain "*/*" as bytea;

create or replace function api.file(_id int) returns "*/*" as $$
  declare v_headers text;
  declare v_blob    bytea;
  begin
    select format(
      '[{"Content-Type": "%s"},'
       '{"Content-Disposition": "inline; filename=\"%s\""},'
       '{"Cache-Control": "max-age=259200"}]'
      , type, name)
    from file where id = _id into v_headers;
    perform set_config('response.headers', v_headers, true);
    select blob from file where id = _id into v_blob;
    if FOUND -- special var, see https://www.postgresql.org/docs/current/plpgsql-statements.html#PLPGSQL-STATEMENTS-DIAGNOSTICS
    then return(v_blob);
    else raise sqlstate 'PT404' using
      message = 'NOT FOUND',
      detail = 'File not found',
      hint = format('%s seems to be an invalid file id', _id);
    end if;
  end
$$ language plpgsql;

create or replace function api.images() returns "text/html" as $$
  select $html$
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>PostgREST Images</title>
      <style>
        img {
          width: 300px;
          height: 300px;
          object-fit: contain;
        }
      </style>
    </head>
    <body>
      <img src="http://localhost:3000/rpc/file?_id=1" alt="Postgres">
      <img src="http://localhost:3000/rpc/file?_id=2" alt="Ted Codd">
    </body>
    </html>
  $html$;
$$ language sql;