<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Htmx.fs" />
    <Compile Include="Mvc.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Falco" Version="5.*" />
    <PackageReference Include="Falco.Htmx" Version="1.2.0" />
  </ItemGroup>
</Project>
